:imagesdir: ../images

:toc: macro
:toc-title:

toc::[]

== Opentracing

TODO: Information about opentracing and how to use the experimental Java provider


== Zipkin

Zipkin project contains many instrumentation libraries for several programing languages, therefore it makes it easy to get tracing data for polyglot applications. Hawkular APM is compatible with zipkin collectors so any application instrumented with zipkin library can report data to Hawkular APM. 

Zipkin is not strictly a standard API, but could be considered a defacto standard. The zipkin project defines a standard span format for reporting information to the Zipkin server, and a standard format for propagating information between interacting services.

===== Configuration
Http collector is enabled by default. Kafka collector can be enabled by setting environmental variable `KAFKA_ZOOKEEPER`. It is zookeeper connect string, ex. `127.0.0.1:2181`.

-----
$ KAFKA_ZOOKEEPER=127.0.0.1 bin/standalone.sh -Djboss.http.port=8080
-----

If you are already using zipkin in your environment change the binding port to `9411` and trace data will be reported to APM.

==== Links
* List of zipkin http://zipkin.io/pages/existing_instrumentations.html[instrumentation libraries]
* Zipkin libraries usage https://github.com/hawkular/hawkular-apm/tree/master/examples/polyglot-zipkin[examples]
* Zipkin organization on https://github.com/openzipkin[Github]



A number of http://zipkin.io/pages/existing_instrumentations.html[client libraries] have been developed in different programming languages, which has made it ideal as a distributed tracing solution for polyglot applications.

The Zipkin gateway is an integral part of the Hawkular APM server.

All you will need to do to report information from the Zipkin instrumented applications, to the Hawkular APM server, is simply use the Hawkular APM server URL instead of the Zipkin URL.



