:imagesdir: ../images

:toc: macro
:toc-title:

toc::[]

The server can be obtained in two ways, from a downloadable distribution or as a Docker image. This section will describe both approaches.

== Distribution

=== Prerequisites

==== Java 8

You need a Java Virtual Machine compatible with Java 8.

=== Obtaining the distribution

Check out the https://github.com/hawkular/hawkular-apm/releases[Hawkular APM releases] page and download the latest
version of the distribution zip file: `hawkular-apm-dist-X.Y.Z.zip`

Unpack the zip file.

=== Starting the Server

When the server is first unpacked, it will not be configured with any users. Therefore the first command to perform from the distribution's root folder is:

[source,shell]
----
bin/add-user.sh
----

This script will ask a series of questions before creating the user. Ensure that the user is an "Application User" (option b). When asked for the comma separated list of groups, enter:

----
read-write,read-only
----

This will enable the user to be able to report trace fragment information, and also view the results in the UI.

If using the server to display information captured using zipkin client libraries, then the username/password will only be required to access the user interface (UI).

However, if intending to use the _non-intrusive_ java agent based instrumentation mechanism, to observe the activity within a JVM based application, then an example script called _apm/setenv.sh_ is provided to get you up and running quickly. If you intend to use this script, it is preconfigured with a default user (*_jdoe_* with password *_password_*), so you should use these credentials when adding the user to the server.

NOTE: When attempting to use the password *password*, the server will ask you if you are sure, as this is not a secure password to use. Just type 'yes' and it will continue as normal.

When starting the Hawkular APM server we may need to specify a port offset to avoid conflicts with other applications using the default port 8080. The command to start the server, from the root folder of the distribution, will be:

[source,shell]
----
bin/standalone.sh -Djboss.socket.binding.port-offset=100
----

NOTE: The script _apm/setenv.sh_ is preconfigured to use a URL for an APM server on the localhost with port 8180, and therefore a port offset of 100 should be used if intending to use this script when instrumenting applications.


== Docker

To run a server using the docker image, use the following command:

[source,shell]
----
docker run -t -i -p {port}:8080 jboss/hawkular-apm-server
----

This will start a server at port specified by the _{port}_ parameter. For example *-p 8180:8080* would start the APM server at local port 8180.

Just before the server starts, it will display the following message providing the credentials for an initial user created in the server:

[source,shell]
----
ATTENTION ATTENTION ATTENTION ATTENTION
We automatically created an admin user for you to access the Hawkular APM web interface:
Username: {Auto generated username}
Password: {Auto generated password}
----

These credentials should be used when logging into the APM console or when accessing the REST services.

NOTE: If you want a server with a pre-configured username and password (e.g. for development and testing purposes), then use the _jboss/hawkular-apm-server_ image which uses the default username *jdoe* and password *password*.


