:imagesdir: ../images

:toc: macro
:toc-title:

toc::[]

== Prerequisites

=== Java 8

You need a Java Virtual Machine compatible with Java 8.

== Obtaining the distribution

Check out the https://github.com/hawkular/hawkular-apm/releases[Hawkular APM releases] page and download the latest
version of the distribution zip file: `hawkular-apm-dist-X.Y.Z.zip`

Unpack the zip file.

== Starting the Server

The distribution contains some environment scripts for configuring the client-side collection mechanism. These scripts by default will report the information to _localhost_ and _port 8180_ (to avoid conflict with other web apps that may be using the default _8080 port_).

Therefore when starting the Hawkular APM server we will need to specify a port offset. The command to start the server, from the root folder of the distribution, will be:

[source,shell]
----
bin/standalone.sh -Djboss.socket.binding.port-offset=100
----

When the server is initially started, a default user profile is included within the distribution that includes a single user *_jdoe_* with password *_password_*.


