:imagesdir: ../images

Quickstart
----------

=== Docker

To start and bind to localhost:8080

[source,shell]
----
docker run -p 8080:8080 jboss/hawkular-apm-server-dev
----

This docker image starts a server with preconfigured user `jdoe` and password `password`.

=== Binary Release

Download and unpack the latest `hawkular-apm-dist` distribution from https://github.com/hawkular/hawkular-apm/releases[Hawkular APM releases].

From the distribution's root folder:

[source,shell]
----
bin/add-user.sh -a -u jdoe -p password -g read-write,read-only
bin/standalone.sh -b 0.0.0.0 -Djboss.http.port={PORT} // <1>
----
<1> The default port should be `8080`, but if a different port is required (e.g. `9411` for zipkin clients) then it can be set here.


=== Source Build

[source,shell]
----
git clone https://github.com/hawkular/hawkular-apm.git
cd hawkular-apm
mvn clean install -Pdev -DskipTests // <1>
cd dist/target/hawkular-apm-dist-${version}
bin/standalone.sh -b 0.0.0.0 -Djboss.http.port={PORT} // <2>
----
<1> The `-Pdev` argument will build a development distribution containing the default user `jdoe` with password `password`.
<2> The default port should be `8080`, but if a different port is required (e.g. `9411` for zipkin clients) then it can be set here.


= Instrumenting your Application

=== Explicit instrumentation

====== Zipkin

If your applcation is instrumented using http://zipkin.io/pages/existing_instrumentations.html[Zipkin compliant client libraries] then simply update your Zipkin URL to point to the Hawkular APM server (e.g. http://localhost:8080 if running all on the local machine).


====== Opentracing

NOTE: Currently restricted to Java support.

If your application is instrumented using the http://opentracing.io[Opentracing API], then include the following dependencies in your `pom.xml`:

[source,xml]
----
    <dependency>
      <groupId>org.hawkular.apm</groupId>
      <artifactId>hawkular-apm-client-opentracing</artifactId>
      <version>${version.org.hawkular.apm}</version>
    </dependency>
    <dependency>
      <groupId>org.hawkular.apm</groupId>
      <artifactId>hawkular-apm-trace-publisher-rest-client</artifactId>
      <version>${version.org.hawkular.apm}</version>
    </dependency>
----


==== Non-intrusive instrumentation using Java Agent

====== Using script from binary release

[source,shell]
----
. ${APM_HOME}/apm/setenv.sh port   // <1>
----
<1> Where `port` must match the port used for the APM server.

This script configures some environment variables and `JAVA_OPTS` to enable an agent to non-intrusively instrument your application and send the details to the APM server. After executing the script, run your Java application supplying the `JAVA_OPTS` environment variable.

====== Setting up the agent manually

Download the latest `hawkular-apm-agent.jar` from https://github.com/hawkular/hawkular-apm/releases[Hawkular APM releases].

[source,shell]
----
export HAWKULAR_APM_URI=http://localhost:8080 // <1>
export HAWKULAR_APM_USERNAME=jdoe // <2>
export HAWKULAR_APM_PASSWORD=password // <2>
export JAVA_OPTS="-javaagent:${PATH_TO}/hawkular-apm-agent.jar" // <3>

# Wildfly specific
export JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,org.hawkular.apm.instrumenter,org.hawkular.apm.client.collector"

java $JAVA_OPTS ....... // <4>
----

<1> Set this URL to point to the APM server.
<2> Assumes the default username and password have been configured in the APM server.
<3> Must define the path to the `hawkular-apm-agent.jar`
<4> Add the `$JAVA_OPTS` environment variable to your Java command line




