:imagesdir: ../images

:toc: macro
:toc-title:

toc::[]

== Prerequisites

=== Java 8

You need a Java Virtual Machine compatible with Java 8.

== Obtaining the distribution

Check out the https://github.com/hawkular/hawkular-apm/releases[Hawkular APM releases] page and download the latest
version of the distribution zip file: `hawkular-apm-dist-X.Y.Z.zip`

Unpack the zip file.

== Starting the Server

When the server is first unpacked, it will not be configured with any users. Therefore the first command to perform from the distribution's root folder is:

[source,shell]
----
bin/add-user.sh -a -u MyUser -p MyPassword -g read-write,read-only
----

The groups specified with the _-g_ option will enable the user to be able to report trace fragment information, and also view the results in the UI.

If using the server to display information captured using zipkin client libraries, then the username/password will only be required to access the user interface (UI).

However, if intending to use the link:../instrumentation/jvmagent.adoc[JVM Agent] based instrumentation mechanism, or the Hawkular APM opentracing provider, then an example script called _apm/setenv.sh_ is provided to get you up and running quickly.

The command to start the server, from the root folder of the distribution, will be:

[source,shell]
----
bin/standalone.sh -b 0.0.0.0 -Djboss.http.port={PORT} // <1>
----
<1> The default port should be `8080`, but if a different port is required (e.g. `9411` for zipkin clients) then it can be set here.

NOTE: The script _apm/setenv.sh_ is preconfigured to use a URL for an APM server on the localhost with supplied port number (usually 8080). If you intend to use this script, it is preconfigured with a default user (*_jdoe_* with password *_password_*), so you should use these credentials when adding the user to the server.


